[build]
  base = "./.11ty/"
  command = "npm run build"
  publish = "./_site/"

  # The magic bit: 
  # This command returns '1' (trigger build) if there are changes 
  # in the root, excluding the build output folder itself.
  ignore = "git diff --quiet HEAD^ HEAD ../"
