[project]
site_name = "Bytes and Bacteria"
site_description = "Yet another microbinfie blog"
site_url = "https://tomdstanton.github.io/tomdstanton/"
repo_url = "https://github.com/tomdstanton/tomdstanton"
repo_name = "tomdstanton/tomdstanton"
site_author = "Tom Stanton"
edit_uri = "edit/master/docs/"
docs_dir = "docs"
site_dir = "site"
copyright = """
Copyright &copy; 2026 <a href="https://tomdstanton.com" target="_blank">Tom Stanton</a>
"""
extra_css = ["stylesheets/extra.css"]
nav = [
    { "Home" = "index.md" },
    { "Blog Posts" = [
        { "The Journey So Far" = "posts/journey.md" },
        { "You like 'Huey Lewis and the News?" = "posts/soas.md" }
    ]},
    { "Bibliography" = "bib.md" },
]
plugins = [
    "search",
    { reading-time = { words_per_minute = 200 } },
    "include-markdown",
    "offline",
]
extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
]

[project.theme]
name = "material"
custom_dir = "docs/overrides"
logo = "assets/logo.png"
favicon = "assets/logo.png"
language = "en"
features = [
    "announce.dismiss",
    "content.action.edit",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "header.autohide",
    "navigation.top",
    "navigation.footer",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.tracking",
    # "navigation.sections",
    # "navigation.expand",
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.path",
    "search.suggest",
    "search.highlight",
    "search.share",
    "toc.follow",
    # "toc.integrate",
]

[project.theme.font]
text = "Manrope"
code = "IBM Plex Mono"

[project.theme.icon]
repo = "fontawesome/brands/github"
# logo = "lucide/dna"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
primary = "custom"
accent = "custom"
toggle.icon = "lucide/sun-moon"
toggle.name = "Use light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
primary = "custom"
accent = "custom"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Use dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
primary = "custom"
accent = "custom"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Use system preference"

[project.extra]
social = [
    { icon = "lucide/mail", link = "mailto:tomdstanton@gmail.com" },
]
generator = false

[project.markdown_extensions]
admonition = {}
attr_list = {}
footnotes = {}
md_in_html = {}
toc = { permalink = true, title = "On this page" }
"pymdownx.arithmatex" = { generic = true }
"pymdownx.details" = {}
"pymdownx.emoji" = { emoji_index = "zensical.extensions.emoji.twemoji", emoji_generator = "zensical.extensions.emoji.to_svg" }
"pymdownx.highlight" = { anchor_linenums = true, use_pygments = true, linenums = true, auto_title = true }
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = { base_path = ["."] }
"pymdownx.superfences" = { custom_fences = [ { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" } ] }
"pymdownx.tabbed" = { alternate_style = true }
"zensical.extensions.glightbox" = {}
