[project]
site_name = "Bytes and Bacteria"
site_description = "Yet another microbinfie blog"
site_url = "https://tomdstanton.github.io/tomdstanton/"
repo_url = "https://github.com/tomdstanton/tomdstanton"
repo_name = "tomdstanton/tomdstanton"
site_author = "Tom Stanton"
docs_dir = "docs"
site_dir = "site"
language = "en"
copyright = """
Copyright &copy; 2026 <a href="https://tomdstanton.com" target="_blank">Tom Stanton</a>
"""
nav = [
    { "Home" = "index.md" },
    # { "Tags" = "tags.md" },
    { "Blog Posts" = [
        { "About me" = "posts/about_me.md" },
        { "You like 'Huey Lewis and the News?" = "posts/soas.md" }
    ]}
]
watch = ["zensical.toml", "README.md", "docs"]
plugins = [
  "search",
  "include-markdown",
  "offline"
]
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/tomdstanton/tomdstanton"

[project.theme]
icon.repo = "fontawesome/brands/github"
icon.logo = "lucide/dna"
# font.text = "Noto Sans"
font.code = "JetBrains Mono"
features = [
    "announce.dismiss",
    "content.action.edit",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "header.autohide",
    "navigation.top",
    "navigation.footer",
    "navigation.tabs",
    "navigation.tracking",
    "navigation.sections",
    "navigation.expand",
    "navigation.instant",
    "navigation.instant.progress",
    "search.suggest",
    "search.highlight",
    "search.share",
    "toc.follow",
    "toc.integrate",
]

# System default (Auto) state
[theme.palette.toggle]
icon = "lucide/sun-moon"
hint = "Switch to dark mode"
name = "auto"

# Light mode state
[theme.palette.toggle.light]
icon = "lucide/sun"
hint = "Switch to light mode"
name = "light"

# Dark mode state
[theme.palette.toggle.dark]
icon = "lucide/moon"
hint = "Switch to system preference"
name = "dark"

[project.markdown_extensions]
admonition = {}
"pymdownx.details" = {}
"pymdownx.tabbed" = { alternate_style = true }
"pymdownx.highlight" = { anchor_linenums = true, use_pygments = true }
"pymdownx.inlinehilite" = {}
"pymdownx.arithmatex" = { generic = true }
toc = { permalink = true, title = "On this page" }
footnotes = {}

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.zensical.extensions.glightbox]

